# Generated by Django 2.1.4 on 2018-12-09 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodsense',
            name='location_id',
        ),
        migrations.AddField(
            model_name='moodsense',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
